Repository CA22-game-creators/cookingbomb-proto, pull requests merged in 2021-06, with the labels that each got.

#21 feat: アカウント名の正規表現を変更
  doc/specification.md
  proto/api/message.proto
  server/pb/api/message.pb.go
  server/pb/api/model.pb.go
  server/pb/api/service.pb.go
  server/pb/common/option.pb.go
  server/pb/game/message.pb.go
  server/pb/game/model.pb.go
  server/pb/game/service.pb.go
  server/pb/game/structure.pb.go
  test/testdata/pb/string.pb.go
Labels: change, ship it!

#24 feat: エンドポイントごとにエラーメッセージを指定できるように
  .github/workflows/test.yaml
  Makefile
  go.mod
  go.sum
  proto/api/message.proto
  proto/common/option.proto
  proto/game/message.proto
  server/pb/api/message.pb.go
  server/pb/common/option.pb.go
  server/pb/game/message.pb.go
  server/test/api/get_account_info_test.go
  server/test/api/get_session_token_test.go
  server/test/api/signup_test.go
  server/test/game/connection_test.go
  server/test/game/game_data_stream_test.go
  server/validation/string.go
  server/validation/validator.go
  test/server/validation/validator_test.go
  test/testdata/pb/string.pb.go
  test/testdata/string.proto
Labels: refactor, レビュー待ち

#25 doc: ゲームサーバーのリファレンスを追加
  doc/game-server/README.md
Labels: doc, ship it!
