Repository CA22-game-creators/cookingbomb-proto, pull requests merged in 2021-05, with the labels that each got.

#2 feat: ユーザ登録処理のproto実装
  Makefile
  README.md
  proto/message.proto
  proto/model.proto
  proto/option.proto
  proto/service.proto
  server/go.mod
  server/go.sum
  server/pb/message.pb.go
  server/pb/model.pb.go
  server/pb/option.pb.go
  server/pb/service.pb.go
  server/pb/service_grpc.pb.go
Labels: implement, レビュー待ち

#5 fix: go importできない
  Makefile
  go.mod
  go.sum
Labels: bugfix, レビュー待ち

#6 fix: goのroot directoryを変更する
  go.mod
Labels: bugfix, レビュー待ち

#9 feat: バリデーション実装(string/len)
  Makefile
  go.mod
  go.sum
  proto/message.proto
  proto/model.proto
  proto/option.proto
  proto/service.proto
  server/pb/message.pb.go
  server/pb/model.pb.go
  server/pb/option.pb.go
  server/pb/service.pb.go
  server/pb/service_grpc.pb.go
  server/validation/string.go
  server/validation/validator.go
  test/server/validation/validator_test.go
  test/testdata/pb/string.pb.go
  test/testdata/string.proto
Labels: implement, ship it!

#11 feat: gameサイドのprotoファイルを定義, Makeファイルを合わせて編集
  Makefile
  proto/game/message.proto
  proto/game/model.proto
  proto/game/service.proto
  server/game/pb/message.pb.go
  server/game/pb/model.pb.go
  server/game/pb/service.pb.go
  server/game/pb/service_grpc.pb.go
Labels: implement, ship it!

#13 update Makefile: クライアント用のコードを追加
  Makefile
  client/pb/Message.cs
  client/pb/Model.cs
  client/pb/Option.cs
  client/pb/Service.cs
  client/pb/game/Message.cs
  client/pb/game/Model.cs
  client/pb/game/Service.cs
Labels: implement, ship it!, レビュー待ち

#15 refactor: protoファイルの構造変更
  Makefile
  client/pb/Message.cs
  client/pb/Model.cs
  client/pb/Option.cs
  client/pb/Service.cs
  client/pb/game/Message.cs
  client/pb/game/Model.cs
  client/pb/game/Service.cs
  go.mod
  go.sum
  proto/api/message.proto
  proto/api/model.proto
  proto/api/service.proto
  proto/common/option.proto
  server/pb/api/message.pb.go
  server/pb/api/model.pb.go
  server/pb/api/service.pb.go
  server/pb/api/service_grpc.pb.go
  server/pb/common/option.pb.go
  server/pb/game/message.pb.go
  server/pb/game/model.pb.go
  server/pb/game/service.pb.go
  server/pb/game/service_grpc.pb.go
  server/pb/option.pb.go
  server/pb/service.pb.go
  server/validation/string.go
  server/validation/validator.go
  test/testdata/pb/string.pb.go
  test/testdata/string.proto
Labels: refactor, ship it!

#16 update proto/game: 定義を更新
  go.sum
  proto/game/message.proto
  proto/game/model.proto
  proto/game/service.proto
  proto/game/structure.proto
  server/pb/game/message.pb.go
  server/pb/game/model.pb.go
  server/pb/game/service.pb.go
  server/pb/game/service_grpc.pb.go
  server/pb/game/structure.pb.go
Labels: implement, ship it!

#17 feat: 認証周りのproto作成
  README.md
  doc/development.md
  doc/specification.md
  go.mod
  go.sum
  proto/api/message.proto
  proto/api/model.proto
  proto/api/service.proto
  proto/common/option.proto
  server/pb/api/message.pb.go
  server/pb/api/model.pb.go
  server/pb/api/service.pb.go
  server/pb/api/service_grpc.pb.go
  server/pb/common/option.pb.go
  server/validation/string.go
  test/server/validation/validator_test.go
  test/testdata/pb/string.pb.go
  test/testdata/string.proto
Labels: implement, レビュー待ち
